config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "job_executions#index"
  resources :job_executions
  resources :jobs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :users
end

app/models/job.rb
class Job < ApplicationRecord

end

app/models/job_execution.rb
class JobExecution < ApplicationRecord
  belongs_to :job
  belongs_to :user
  belongs_to :division

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :division
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:division_id, :first_name, :last_name])
  end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
end

app/controllers/job_executions_controller.rb
class JobExecutionsController < ApplicationController
  before_action :find_job_executions, only: %i[index]
  
  def index

  end

  def new
    @division = Division.all
    @job_execution = JobExecution.new
  end

  def create
    @new_job = JobExecution.new(job_execution_params)
    if @new_job.save
    else 
      render :new
    end
  end

  private

  def find_job_executions
    @job_executions = JobExecution.all
  end

  def job_execution_params
    params.require(:job_execution).permit(:explanation, :urgent, :division_id, :user_id, :job_id )
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/job_executions_helper.rb
module JobExecutionsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/job_executions/_form.html.erb
<%= form_with model: [@job_execution], local: true do |f| %>
  <%= f.label(:explanation, "Описание") %>
  <%= f.text_area :explanation, size: "40x5" %>
  <br>
  <%= f.label(:urgent, "Срочно!") %>
  <%= f.check_box :urgent,{ checked: false }, 'true', 'false' %>
  <br>
  <%= f.label :division %>
        <div class="dropdown">
  <%= f.collection_select :division_id, Division.order(:name), :id, :name,
  class: "btn btn-secondary dropdown-toggle"%>
        </div>
  <br>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <br>
  <%= f.label :job_id %>
        <div class="dropdown">
  <%= f.collection_select :job_id, Job.order(:name), :id, :name, 
  class: "btn btn-secondary dropdown-toggle"%>
        </div>
  

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/job_executions/_job_execution.html.erb
<tr>
  <td><%= job_execution.division.name %></td>
  <td><%= job_execution.job.name %></td>
  <td><%= job_execution.explanation %></td>
  <td><%= job_execution.user.first_name  %></td>
  <td><%= job_execution.urgent ? 'Да' : 'Нет' %></td>
  <td><%= button_to 'Выполнено', job_execution_path(job_execution) %></td>
  <td><%= button_to 'Удалить', job_execution_path(job_execution) %></td>
</tr>

app/views/job_executions/index.html.erb
<h1 class="text-center mt-3"> Список заявок </h1>

<table class='table table-striped'>
    <tr>
        <th>Объект</th>
        <th>Название</th>
        <th>Описание</th>
        <th>Пользователь</th>
        <th>Срочно</th>
        <th colspan="2" >Действие</th>
    </tr>

    <%= render @job_executions %>
    
</table>

app/views/job_executions/new.html.erb
<h1>Создание заявки</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/jobs/index.html.erb
jobs
<br>
<%= @jobs %>
<%= @user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ira</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">СИТЕМА ЗАЯВОК</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Заявки
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li> <%= link_to "Создать заявку", new_job_execution_path, class: "dropdown-item" %> </li>
            <li> <%= link_to "Мои заявки", job_executions_path, class: "dropdown-item" %> </li>
          </ul>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="#">О системе</a>
        </li>
      </ul>
    </div>

    <span class="navbar-text">
    <% if user_signed_in? %>
      Привет, <b><%= current_user.first_name %></b>
      <%= link_to "Выйти", destroy_user_session_path, method: :delete %>
    <% else %>  
      <%= link_to "Войти", new_user_session_path %> |
      <%= link_to "Регистрация", new_user_registration_path %>
    <% end %>
  </span>
  </div>



</nav>